name: Master-Mirror

on:
  schedule:
    - cron: '33 3,15 * * *'
  workflow_dispatch:

jobs:
  mirror_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - name: Update mirror
        run: |
          git remote add upstream https://git.savannah.gnu.org/git/gnuzilla.git
          git fetch --tags upstream
          git pull upstream master
          git push --tags --set-upstream origin master
          gh workflow run release.yml --ref main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
