name: Master-Mirror

on:
  schedule:
    - cron: '33 3 * * *'
  workflow_dispatch:

jobs:
  mirror_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - name: Add remote
        run: git remote add upstream https://git.savannah.gnu.org/git/gnuzilla.git
      - name: Fetch all
        run: git fetch --tags upstream
      - name: Pull upstream
        run: git pull upstream master
      - name: Push update
        run: git push --tags --set-upstream origin master
